# Default values for swebdeploy.

image:
  repository: "acrinterview.azurecr.io/simple-web"
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: "swebdeploy"
fullnameOverride: "simple-web-deploy"
namespace: "shai"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - paths:
    - path: /shai
      pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

