# Default values for swebdeploy.

image:
  repository: "acrinterview.azurecr.io/simple-web"
  pullPolicy: IfNotPresent
  tag: "latest"
  containerPort: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespace: "shai"

service:
  type: LoadBalancer
  port: 80
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

ingress:
  enabled: false


resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

