# Default values for swebdeploy.

image:
  repository: "acrinterview.azurecr.io/simple-web"
  pullPolicy: IfNotPresent
  tag: "latest"
  containerPort: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespace: "shai"

service:
  type: NodePort
  port: 80
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

