apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "swebdeploy.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ include "swebdeploy.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  triggers:
  - type: cron
    metadata:
      timezone: "Asia/Jerusalem"
      start: "0 8 * * *"
      end: "0 0 * * *"
      desiredReplicas: {{ .Values.autoscaling.maxReplicas | quote }}
  - type: cpu
    metadata:
      type: Utilization
      value: {{ .Values.autoscaling.targetCPUUtilizationPercentage | quote }}
  - type: memory
    metadata:
      type: Utilization
      value: {{ .Values.autoscaling.targetMemoryUtilizationPercentage | quote }}
